export const allInstruments = JSON.parse`[
  {
    "id": "553eab2b-400d-4f16-9e61-a5baa7068b9d",
    "name": "Daxophone",
    "price": 367,
    "descript": "orchestrate virtual solutions",
    "image": "https://robohash.org/temporedolorsed.png?size=50x50&set=set1",
    "stock": 6,
    "color": "Puce",
    "categorie": "wind",
    "brand": "Fender"
  },
  {
    "id": "3736a8cf-2f0e-4574-883a-eab5fd29b651",
    "name": "Guitarra semi acústica",
    "price": 408,
    "descript": "whiteboard killer metrics",
    "image": "https://robohash.org/quasiutsit.png?size=50x50&set=set1",
    "stock": 14,
    "color": "Crimson",
    "categorie": "percussion",
    "brand": "Gibson"
  },
  {
    "id": "cea152a4-80a3-4fe4-ae5a-e626c7a5e181",
    "name": "Quena",
    "price": 330,
    "descript": "repurpose seamless eyeballs",
    "image": "https://robohash.org/nihilautemaut.png?size=50x50&set=set1",
    "stock": 11,
    "color": "Crimson",
    "categorie": "wind",
    "brand": "Squier"
  },
  {
    "id": "d57e162e-81b4-4e71-95d9-6fa9dbad011b",
    "name": "Gong",
    "price": 280,
    "descript": "maximize 24/7 networks",
    "image": "https://robohash.org/doloribusipsumcorrupti.png?size=50x50&set=set1",
    "stock": 17,
    "color": "Goldenrod",
    "categorie": "wind",
    "brand": "Yamaha"
  },
  {
    "id": "e1f7625d-8ca8-4773-a0b7-bd3a1cc0435a",
    "name": "Contrabajo",
    "price": 211,
    "descript": "embrace granular portals",
    "image": "https://robohash.org/etculpanon.png?size=50x50&set=set1",
    "stock": 9,
    "color": "Turquoise",
    "categorie": "string",
    "brand": "Yamaha"
  },
  {
    "id": "08dd3015-1dec-4b02-8ba7-61c964ffddad",
    "name": "Tabla",
    "price": 216,
    "descript": "harness transparent relationships",
    "image": "https://robohash.org/fugitmodiullam.png?size=50x50&set=set1",
    "stock": 20,
    "color": "Maroon",
    "categorie": "wind",
    "brand": "PRS"
  },
  {
    "id": "53bf90c9-1c36-4d2d-a80f-df5b36d29f67",
    "name": "Mandolina",
    "price": 207,
    "descript": "strategize e-business initiatives",
    "image": "https://robohash.org/velitenimea.png?size=50x50&set=set1",
    "stock": 16,
    "color": "Turquoise",
    "categorie": "idiophones",
    "brand": "Gibson"
  },
  {
    "id": "0a790a82-0d9b-43c3-977a-b21f1fb0f0cb",
    "name": "Tambor tenor",
    "price": 369,
    "descript": "morph end-to-end markets",
    "image": "https://robohash.org/solutaquisquamsit.png?size=50x50&set=set1",
    "stock": 9,
    "color": "Khaki",
    "categorie": "percussion",
    "brand": "Yamaha"
  },
  {
    "id": "869059f1-79af-4ee2-87f8-7fb79c19ffd0",
    "name": "Banjo",
    "price": 467,
    "descript": "exploit visionary web services",
    "image": "https://robohash.org/impeditprovidentalias.png?size=50x50&set=set1",
    "stock": 10,
    "color": "Puce",
    "categorie": "string",
    "brand": "PRS"
  },
  {
    "id": "9e1e5e83-462f-4a24-ba56-3a360e3f9769",
    "name": "Maracas",
    "price": 242,
    "descript": "repurpose viral mindshare",
    "image": "https://robohash.org/quodvoluptasdicta.png?size=50x50&set=set1",
    "stock": 8,
    "color": "Violet",
    "categorie": "electrophones",
    "brand": "Squier"
  },
  {
    "id": "89dd0006-1bfb-42c2-9ac8-8fa81c856783",
    "name": "Timbales",
    "price": 352,
    "descript": "enable revolutionary content",
    "image": "https://robohash.org/utomnisquidem.png?size=50x50&set=set1",
    "stock": 3,
    "color": "Green",
    "categorie": "string",
    "brand": "Peavey"
  },
  {
    "id": "e8f7e860-adf4-4882-80b9-b4ba2bafd475",
    "name": "Violín",
    "price": 316,
    "descript": "seize robust e-commerce",
    "image": "https://robohash.org/beataequiaomnis.png?size=50x50&set=set1",
    "stock": 16,
    "color": "Crimson",
    "categorie": "idiophones",
    "brand": "PRS"
  },
  {
    "id": "0f4c56e3-d4ad-4eff-bdf9-d6903d73d2a5",
    "name": "Mandolina eléctrica",
    "price": 124,
    "descript": "iterate revolutionary e-commerce",
    "image": "https://robohash.org/iurenihilsed.png?size=50x50&set=set1",
    "stock": 1,
    "color": "Red",
    "categorie": "string",
    "brand": "Squier"
  },
  {
    "id": "7c286b91-0374-4dbc-aca7-797c0dbc00fe",
    "name": "Piano Rhodes",
    "price": 442,
    "descript": "harness back-end functionalities",
    "image": "https://robohash.org/etquisquasi.png?size=50x50&set=set1",
    "stock": 17,
    "color": "Aquamarine",
    "categorie": "electrophones",
    "brand": "Fender"
  },
  {
    "id": "0a7f4962-8b57-44cd-9a63-2e557a86fc1d",
    "name": "Bodhran",
    "price": 332,
    "descript": "synthesize cross-platform models",
    "image": "https://robohash.org/aututillo.png?size=50x50&set=set1",
    "stock": 12,
    "color": "Mauv",
    "categorie": "wind",
    "brand": "Peavey"
  },
  {
    "id": "7b339977-0a2e-4701-a604-90fee74f91f9",
    "name": "Pianet",
    "price": 421,
    "descript": "morph mission-critical platforms",
    "image": "https://robohash.org/sintenimnecessitatibus.png?size=50x50&set=set1",
    "stock": 17,
    "color": "Indigo",
    "categorie": "string",
    "brand": "Epiphone"
  },
  {
    "id": "314c5c7e-cc76-4aa4-86e4-e1727d40b3c1",
    "name": "Guitarra de acero de consola",
    "price": 170,
    "descript": "mesh extensible technologies",
    "image": "https://robohash.org/eosexcepturiiusto.png?size=50x50&set=set1",
    "stock": 13,
    "color": "Indigo",
    "categorie": "electrophones",
    "brand": "PRS"
  },
  {
    "id": "8dc140ce-65cf-4aad-b9bb-3588976aca79",
    "name": "Xilófono",
    "price": 191,
    "descript": "repurpose wireless metrics",
    "image": "https://robohash.org/undesitnobis.png?size=50x50&set=set1",
    "stock": 10,
    "color": "Fuscia",
    "categorie": "percussion",
    "brand": "Gibson"
  },
  {
    "id": "059b2ca4-9ce8-4ee5-89f3-0c89535b44c0",
    "name": "Viola",
    "price": 109,
    "descript": "streamline leading-edge communities",
    "image": "https://robohash.org/etincidunteos.png?size=50x50&set=set1",
    "stock": 18,
    "color": "Orange",
    "categorie": "percussion",
    "brand": "Squier"
  },
  {
    "id": "60ba16b3-40cb-4ca3-b899-0727970229ab",
    "name": "Banjo",
    "price": 306,
    "descript": "enhance enterprise methodologies",
    "image": "https://robohash.org/hicveniamest.png?size=50x50&set=set1",
    "stock": 11,
    "color": "Purple",
    "categorie": "idiophones",
    "brand": "Fender"
  },
  {
    "id": "81ec8c70-7d22-4fa0-a2ce-875cfcd047f7",
    "name": "Violín eléctrico",
    "price": 381,
    "descript": "extend granular eyeballs",
    "image": "https://robohash.org/eosetfuga.png?size=50x50&set=set1",
    "stock": 8,
    "color": "Crimson",
    "categorie": "string",
    "brand": "Yamaha"
  },
  {
    "id": "08c86720-fde0-4c21-995d-be69b8d51e0d",
    "name": "Balalaika",
    "price": 345,
    "descript": "facilitate strategic vortals",
    "image": "https://robohash.org/quiremeveniet.png?size=50x50&set=set1",
    "stock": 12,
    "color": "Violet",
    "categorie": "percussion",
    "brand": "PRS"
  },
  {
    "id": "0a91ea99-333c-4c05-99c8-9fbae2c0e254",
    "name": "Pianet",
    "price": 199,
    "descript": "enhance holistic eyeballs",
    "image": "https://robohash.org/temporanisicupiditate.png?size=50x50&set=set1",
    "stock": 14,
    "color": "Fuscia",
    "categorie": "string",
    "brand": "Yamaha"
  },
  {
    "id": "ef9c6d32-4b4c-4f62-9121-25197fb09242",
    "name": "Piano eléctrico",
    "price": 387,
    "descript": "enable frictionless systems",
    "image": "https://robohash.org/etquaeratunde.png?size=50x50&set=set1",
    "stock": 13,
    "color": "Purple",
    "categorie": "idiophones",
    "brand": "Yamaha"
  },
  {
    "id": "1fa8f84b-5d13-43d2-a451-01c00662f829",
    "name": "El triángulo",
    "price": 306,
    "descript": "visualize best-of-breed applications",
    "image": "https://robohash.org/quasrepellendusiure.png?size=50x50&set=set1",
    "stock": 9,
    "color": "Violet",
    "categorie": "electrophones",
    "brand": "Yamaha"
  },
  {
    "id": "7817a1e7-945c-44d6-b0a1-551dd0328614",
    "name": "Banjo",
    "price": 221,
    "descript": "harness web-enabled models",
    "image": "https://robohash.org/illovoluptatumet.png?size=50x50&set=set1",
    "stock": 10,
    "color": "Red",
    "categorie": "wind",
    "brand": "Gibson"
  },
  {
    "id": "31224127-a032-4d23-bd08-818f3fa93df6",
    "name": "Viola",
    "price": 112,
    "descript": "enhance frictionless paradigms",
    "image": "https://robohash.org/voluptatemoptionostrum.png?size=50x50&set=set1",
    "stock": 2,
    "color": "Pink",
    "categorie": "percussion",
    "brand": "Epiphone"
  },
  {
    "id": "9ec1eea6-e72b-4add-aca5-97b361c8c493",
    "name": "Oboe",
    "price": 389,
    "descript": "transition e-business metrics",
    "image": "https://robohash.org/consequunturfacerequi.png?size=50x50&set=set1",
    "stock": 11,
    "color": "Puce",
    "categorie": "string",
    "brand": "PRS"
  },
  {
    "id": "a56b55ba-2b20-4d6f-8626-69aa83b80839",
    "name": "Oboe",
    "price": 420,
    "descript": "monetize cross-media metrics",
    "image": "https://robohash.org/perspiciatiserrordignissimos.png?size=50x50&set=set1",
    "stock": 1,
    "color": "Blue",
    "categorie": "percussion",
    "brand": "Fender"
  },
  {
    "id": "f5517cdf-1047-4887-918d-705573a399f9",
    "name": "El Chapman Stick",
    "price": 381,
    "descript": "engineer mission-critical interfaces",
    "image": "https://robohash.org/inventoremolestiaein.png?size=50x50&set=set1",
    "stock": 19,
    "color": "Purple",
    "categorie": "idiophones",
    "brand": "Gibson"
  },
  {
    "id": "2edfa7cb-8aff-467b-a7b2-fe6b3addb0a7",
    "name": "Violonchelo eléctrico",
    "price": 205,
    "descript": "grow back-end architectures",
    "image": "https://robohash.org/doloressinthic.png?size=50x50&set=set1",
    "stock": 19,
    "color": "Fuscia",
    "categorie": "wind",
    "brand": "Yamaha"
  },
  {
    "id": "6e6adb1f-e338-490b-8eb6-8c3e3d8d418a",
    "name": "Tin whistle",
    "price": 444,
    "descript": "seize holistic experiences",
    "image": "https://robohash.org/suscipitutipsam.png?size=50x50&set=set1",
    "stock": 6,
    "color": "Goldenrod",
    "categorie": "wind",
    "brand": "Squier"
  },
  {
    "id": "a4005273-f82d-4fe2-bab2-26f9d7a14bd9",
    "name": "Mandolina eléctrica",
    "price": 211,
    "descript": "maximize revolutionary e-services",
    "image": "https://robohash.org/evenietsedquam.png?size=50x50&set=set1",
    "stock": 12,
    "color": "Teal",
    "categorie": "percussion",
    "brand": "Squier"
  },
  {
    "id": "949a8be0-c98e-4937-bc97-991f2f0786fe",
    "name": "Quena",
    "price": 298,
    "descript": "harness strategic e-business",
    "image": "https://robohash.org/etsimiliquedelectus.png?size=50x50&set=set1",
    "stock": 8,
    "color": "Fuscia",
    "categorie": "wind",
    "brand": "Squier"
  },
  {
    "id": "2e87dcab-f3c7-4ca8-9aa7-3047cd6ecdf3",
    "name": "Gaita",
    "price": 159,
    "descript": "iterate enterprise solutions",
    "image": "https://robohash.org/maioresipsamrepellat.png?size=50x50&set=set1",
    "stock": 8,
    "color": "Fuscia",
    "categorie": "percussion",
    "brand": "PRS"
  },
  {
    "id": "ccd4c258-5b88-4922-a0a6-d2108a1bca05",
    "name": "Viola",
    "price": 131,
    "descript": "mesh clicks-and-mortar paradigms",
    "image": "https://robohash.org/possimusillumquia.png?size=50x50&set=set1",
    "stock": 18,
    "color": "Indigo",
    "categorie": "electrophones",
    "brand": "Squier"
  },
  {
    "id": "2b192341-23a9-4898-bdc5-9f00fbfe3cde",
    "name": "Violonchelo eléctrico",
    "price": 283,
    "descript": "engineer rich interfaces",
    "image": "https://robohash.org/nemomagniullam.png?size=50x50&set=set1",
    "stock": 20,
    "color": "Fuscia",
    "categorie": "percussion",
    "brand": "Fender"
  },
  {
    "id": "ab54ba71-efc7-49d2-a7c7-1c31bec4a0bf",
    "name": "Cítara eléctrica",
    "price": 329,
    "descript": "target cross-platform interfaces",
    "image": "https://robohash.org/etconsecteturreprehenderit.png?size=50x50&set=set1",
    "stock": 10,
    "color": "Yellow",
    "categorie": "idiophones",
    "brand": "Peavey"
  },
  {
    "id": "47172dd3-d173-4a38-845a-436537dd7968",
    "name": "Daxophone",
    "price": 201,
    "descript": "enhance dynamic deliverables",
    "image": "https://robohash.org/officianecessitatibusvoluptate.png?size=50x50&set=set1",
    "stock": 1,
    "color": "Goldenrod",
    "categorie": "string",
    "brand": "PRS"
  },
  {
    "id": "1ab9cf84-f577-4f7e-ad7b-0b4233093dac",
    "name": "Flauta",
    "price": 463,
    "descript": "monetize cross-media platforms",
    "image": "https://robohash.org/modiinaliquid.png?size=50x50&set=set1",
    "stock": 7,
    "color": "Pink",
    "categorie": "wind",
    "brand": "Epiphone"
  },
  {
    "id": "f80fad6e-be47-4255-85a1-61c72103d328",
    "name": "Marimba",
    "price": 132,
    "descript": "disintermediate B2B channels",
    "image": "https://robohash.org/consequaturillumoptio.png?size=50x50&set=set1",
    "stock": 8,
    "color": "Teal",
    "categorie": "wind",
    "brand": "Peavey"
  },
  {
    "id": "6ae9c93a-009e-4426-b222-b86740e61be5",
    "name": "Charango",
    "price": 407,
    "descript": "reinvent killer web services",
    "image": "https://robohash.org/quiadeseruntex.png?size=50x50&set=set1",
    "stock": 16,
    "color": "Green",
    "categorie": "wind",
    "brand": "Peavey"
  },
  {
    "id": "7054bce6-f909-40c8-96c9-96de03a98968",
    "name": "Arpa",
    "price": 300,
    "descript": "target one-to-one web-readiness",
    "image": "https://robohash.org/possimusnihilquisquam.png?size=50x50&set=set1",
    "stock": 2,
    "color": "Fuscia",
    "categorie": "electrophones",
    "brand": "Squier"
  },
  {
    "id": "0ecb63f9-fa28-4e9e-a5d4-c4d48c632afc",
    "name": "Contrafagot",
    "price": 253,
    "descript": "integrate end-to-end action-items",
    "image": "https://robohash.org/quiasitquis.png?size=50x50&set=set1",
    "stock": 5,
    "color": "Red",
    "categorie": "electrophones",
    "brand": "Squier"
  },
  {
    "id": "ec45731e-3090-49d2-9552-53e77f1ebef3",
    "name": "Bandurria",
    "price": 208,
    "descript": "synergize distributed bandwidth",
    "image": "https://robohash.org/placeatinciduntrem.png?size=50x50&set=set1",
    "stock": 13,
    "color": "Goldenrod",
    "categorie": "percussion",
    "brand": "Fender"
  },
  {
    "id": "870fb2cf-6004-4851-8dc4-e66e3784e1db",
    "name": "Trompa de los Alpes",
    "price": 485,
    "descript": "extend synergistic functionalities",
    "image": "https://robohash.org/nondignissimoseius.png?size=50x50&set=set1",
    "stock": 10,
    "color": "Red",
    "categorie": "percussion",
    "brand": "Epiphone"
  },
  {
    "id": "8e5bc582-c75f-4d74-8cba-dd431dc1d68a",
    "name": "Bandola",
    "price": 270,
    "descript": "benchmark interactive platforms",
    "image": "https://robohash.org/estofficiainventore.png?size=50x50&set=set1",
    "stock": 6,
    "color": "Goldenrod",
    "categorie": "wind",
    "brand": "Epiphone"
  },
  {
    "id": "a19ad6b6-e9da-467c-b4b2-b11140dd4532",
    "name": "Quena",
    "price": 158,
    "descript": "redefine open-source deliverables",
    "image": "https://robohash.org/praesentiumexcepturitempora.png?size=50x50&set=set1",
    "stock": 9,
    "color": "Orange",
    "categorie": "idiophones",
    "brand": "Squier"
  },
  {
    "id": "57ab60d4-cde4-4aa9-a927-21d017fcbfac",
    "name": "Contrabajo",
    "price": 461,
    "descript": "synergize dynamic models",
    "image": "https://robohash.org/utetomnis.png?size=50x50&set=set1",
    "stock": 16,
    "color": "Red",
    "categorie": "wind",
    "brand": "PRS"
  },
  {
    "id": "8cec6dc5-d8e5-4bd7-8e1f-cdffa7ae738a",
    "name": "Pianola",
    "price": 339,
    "descript": "strategize value-added e-services",
    "image": "https://robohash.org/vitaenisiquisquam.png?size=50x50&set=set1",
    "stock": 4,
    "color": "Maroon",
    "categorie": "wind",
    "brand": "Squier"
  },
  {
    "id": "8d71a6bb-9485-4aba-9405-b4c4fbc47622",
    "name": "Congas",
    "price": 399,
    "descript": "reinvent cutting-edge portals",
    "image": "https://robohash.org/autemofficiisnihil.png?size=50x50&set=set1",
    "stock": 9,
    "color": "Mauv",
    "categorie": "wind",
    "brand": "Squier"
  },
  {
    "id": "0f0c81a4-6352-4e0f-b817-b118d9a4fece",
    "name": "Harpa eléctrica",
    "price": 302,
    "descript": "implement dynamic models",
    "image": "https://robohash.org/utquisunde.png?size=50x50&set=set1",
    "stock": 16,
    "color": "Green",
    "categorie": "idiophones",
    "brand": "Epiphone"
  },
  {
    "id": "cc863c44-52d9-4c32-88ed-7df8d92ff307",
    "name": "Gong",
    "price": 304,
    "descript": "transition plug-and-play technologies",
    "image": "https://robohash.org/quasiinut.png?size=50x50&set=set1",
    "stock": 11,
    "color": "Blue",
    "categorie": "idiophones",
    "brand": "PRS"
  },
  {
    "id": "8e53af70-c892-4115-ab62-096047424afe",
    "name": "Berimbau",
    "price": 159,
    "descript": "deploy open-source ROI",
    "image": "https://robohash.org/omnisnullasaepe.png?size=50x50&set=set1",
    "stock": 14,
    "color": "Orange",
    "categorie": "idiophones",
    "brand": "Squier"
  },
  {
    "id": "e8d139f1-d296-4c7c-a566-6e36bae9862f",
    "name": "Berimbau",
    "price": 115,
    "descript": "recontextualize plug-and-play convergence",
    "image": "https://robohash.org/saepecumquevoluptatum.png?size=50x50&set=set1",
    "stock": 17,
    "color": "Red",
    "categorie": "string",
    "brand": "Fender"
  },
  {
    "id": "8a19dd5e-231f-4548-a282-356cf526ea92",
    "name": "Piano eléctrico",
    "price": 147,
    "descript": "mesh synergistic niches",
    "image": "https://robohash.org/minimaautdolorum.png?size=50x50&set=set1",
    "stock": 5,
    "color": "Blue",
    "categorie": "wind",
    "brand": "Epiphone"
  },
  {
    "id": "8a5884f0-e5ef-4a4e-ae1a-f25020383a4e",
    "name": "Harpa eléctrica",
    "price": 121,
    "descript": "synergize frictionless e-markets",
    "image": "https://robohash.org/cumrerumipsum.png?size=50x50&set=set1",
    "stock": 17,
    "color": "Fuscia",
    "categorie": "wind",
    "brand": "PRS"
  },
  {
    "id": "45b4ccbb-5dfa-41fb-9225-36a7d672abc8",
    "name": "Dulzaina",
    "price": 376,
    "descript": "repurpose holistic solutions",
    "image": "https://robohash.org/providentetnemo.png?size=50x50&set=set1",
    "stock": 16,
    "color": "Aquamarine",
    "categorie": "string",
    "brand": "Gibson"
  },
  {
    "id": "d80930af-c428-4818-8146-de2aac7b342c",
    "name": "Banjo eléctrico",
    "price": 296,
    "descript": "incentivize customized functionalities",
    "image": "https://robohash.org/consectetureligendiodit.png?size=50x50&set=set1",
    "stock": 6,
    "color": "Pink",
    "categorie": "idiophones",
    "brand": "Epiphone"
  },
  {
    "id": "fa7e5c6d-4420-4766-8b52-21f0cfb4d9ef",
    "name": "Guitarra de acero de consola",
    "price": 114,
    "descript": "transform granular models",
    "image": "https://robohash.org/quiremvoluptatibus.png?size=50x50&set=set1",
    "stock": 20,
    "color": "Goldenrod",
    "categorie": "percussion",
    "brand": "PRS"
  },
  {
    "id": "83ed7267-7c63-47c8-ade2-a3c74f73d1aa",
    "name": "Ukelele",
    "price": 449,
    "descript": "iterate cross-media users",
    "image": "https://robohash.org/maioresvoluptasminus.png?size=50x50&set=set1",
    "stock": 11,
    "color": "Aquamarine",
    "categorie": "string",
    "brand": "Epiphone"
  },
  {
    "id": "c3d752ec-ceac-4ec0-baa2-9396534b0b14",
    "name": "Tarka",
    "price": 445,
    "descript": "envisioneer virtual vortals",
    "image": "https://robohash.org/perferendiseoset.png?size=50x50&set=set1",
    "stock": 19,
    "color": "Teal",
    "categorie": "electrophones",
    "brand": "Squier"
  },
  {
    "id": "88e9b5d9-9781-4da6-8a99-45252a33a7ea",
    "name": "El cajón o caja peruana",
    "price": 224,
    "descript": "cultivate cross-platform mindshare",
    "image": "https://robohash.org/doloresedinventore.png?size=50x50&set=set1",
    "stock": 8,
    "color": "Violet",
    "categorie": "idiophones",
    "brand": "Gibson"
  },
  {
    "id": "b0189a58-cea2-4898-8cf3-b7fda1494a23",
    "name": "Tarka",
    "price": 323,
    "descript": "synergize back-end infomediaries",
    "image": "https://robohash.org/consequunturdoloresofficiis.png?size=50x50&set=set1",
    "stock": 20,
    "color": "Mauv",
    "categorie": "string",
    "brand": "Yamaha"
  },
  {
    "id": "46566d76-99e6-4950-92f4-4f497a369d56",
    "name": "Marimba",
    "price": 335,
    "descript": "optimize compelling portals",
    "image": "https://robohash.org/expeditaeaillo.png?size=50x50&set=set1",
    "stock": 12,
    "color": "Crimson",
    "categorie": "wind",
    "brand": "Epiphone"
  },
  {
    "id": "a179623a-9831-49a6-8115-3f71d492d39e",
    "name": "Batería eléctrica",
    "price": 259,
    "descript": "iterate rich solutions",
    "image": "https://robohash.org/beataeidveritatis.png?size=50x50&set=set1",
    "stock": 19,
    "color": "Purple",
    "categorie": "percussion",
    "brand": "Yamaha"
  },
  {
    "id": "ea161f8e-565d-446f-8b0f-080440eb3d8d",
    "name": "Balalaika",
    "price": 302,
    "descript": "monetize turn-key portals",
    "image": "https://robohash.org/teneturliberoimpedit.png?size=50x50&set=set1",
    "stock": 9,
    "color": "Teal",
    "categorie": "electrophones",
    "brand": "Fender"
  },
  {
    "id": "4b6cca47-8b4a-44fe-b247-7f2de7062b70",
    "name": "Dulzaina",
    "price": 262,
    "descript": "expedite cross-media experiences",
    "image": "https://robohash.org/doloreteneturneque.png?size=50x50&set=set1",
    "stock": 11,
    "color": "Green",
    "categorie": "string",
    "brand": "Epiphone"
  },
  {
    "id": "4790f3ac-f1eb-44fd-8b7a-03cf3fc126e3",
    "name": "Rabel",
    "price": 217,
    "descript": "incentivize strategic models",
    "image": "https://robohash.org/eumrepellatest.png?size=50x50&set=set1",
    "stock": 12,
    "color": "Orange",
    "categorie": "percussion",
    "brand": "PRS"
  },
  {
    "id": "756cf254-d50b-456f-b102-3965d4725402",
    "name": "Bandurria",
    "price": 271,
    "descript": "orchestrate B2C infomediaries",
    "image": "https://robohash.org/illoadest.png?size=50x50&set=set1",
    "stock": 5,
    "color": "Violet",
    "categorie": "percussion",
    "brand": "Fender"
  },
  {
    "id": "052b0e73-a432-493c-b5db-9ae4e8df96db",
    "name": "Berimbau",
    "price": 489,
    "descript": "synthesize vertical applications",
    "image": "https://robohash.org/atqueautofficiis.png?size=50x50&set=set1",
    "stock": 7,
    "color": "Goldenrod",
    "categorie": "electrophones",
    "brand": "Gibson"
  },
  {
    "id": "84ce341a-ecc8-4bef-94ff-7659ad60ed87",
    "name": "Mandolina eléctrica",
    "price": 148,
    "descript": "synthesize customized markets",
    "image": "https://robohash.org/temporibusquitotam.png?size=50x50&set=set1",
    "stock": 9,
    "color": "Pink",
    "categorie": "string",
    "brand": "Gibson"
  },
  {
    "id": "51bcc310-f253-452c-8cfa-70c0d6da1fcc",
    "name": "Crótalos",
    "price": 122,
    "descript": "strategize cutting-edge architectures",
    "image": "https://robohash.org/atqueadet.png?size=50x50&set=set1",
    "stock": 3,
    "color": "Puce",
    "categorie": "percussion",
    "brand": "Fender"
  },
  {
    "id": "254d70bd-9111-47b7-9e5b-c39f775ee5ab",
    "name": "El cajón o caja peruana",
    "price": 411,
    "descript": "seize extensible models",
    "image": "https://robohash.org/sedharumprovident.png?size=50x50&set=set1",
    "stock": 12,
    "color": "Blue",
    "categorie": "wind",
    "brand": "Gibson"
  },
  {
    "id": "29b26224-0423-4643-9afe-1f260e675208",
    "name": "Tambor tenor",
    "price": 388,
    "descript": "transition leading-edge portals",
    "image": "https://robohash.org/molestiaenihilrepellendus.png?size=50x50&set=set1",
    "stock": 15,
    "color": "Goldenrod",
    "categorie": "percussion",
    "brand": "Squier"
  },
  {
    "id": "372d5f14-be7e-41ae-810f-52aa8b32642e",
    "name": "Atabaque",
    "price": 336,
    "descript": "reintermediate distributed deliverables",
    "image": "https://robohash.org/fugaametfacilis.png?size=50x50&set=set1",
    "stock": 17,
    "color": "Orange",
    "categorie": "percussion",
    "brand": "Yamaha"
  },
  {
    "id": "b645f8ef-776f-4e31-970e-0828fe732e4f",
    "name": "Trombón",
    "price": 229,
    "descript": "innovate intuitive supply-chains",
    "image": "https://robohash.org/quasdeseruntut.png?size=50x50&set=set1",
    "stock": 1,
    "color": "Mauv",
    "categorie": "electrophones",
    "brand": "Yamaha"
  },
  {
    "id": "c18f98d5-3f56-4420-9277-d45faa6fed2a",
    "name": "Clavicordio",
    "price": 183,
    "descript": "facilitate intuitive applications",
    "image": "https://robohash.org/aspernaturdolorescupiditate.png?size=50x50&set=set1",
    "stock": 14,
    "color": "Turquoise",
    "categorie": "wind",
    "brand": "Fender"
  },
  {
    "id": "b1688752-3ea0-4c0d-b57f-bd1ec4c83f8d",
    "name": "Piano",
    "price": 464,
    "descript": "matrix intuitive platforms",
    "image": "https://robohash.org/voluptatumeoseaque.png?size=50x50&set=set1",
    "stock": 18,
    "color": "Turquoise",
    "categorie": "idiophones",
    "brand": "Fender"
  },
  {
    "id": "9d15c2bb-861e-4c97-ab41-40cca15a8a5b",
    "name": "Tambor tenor",
    "price": 396,
    "descript": "synthesize impactful infrastructures",
    "image": "https://robohash.org/perferendisrepudiandaevoluptate.png?size=50x50&set=set1",
    "stock": 7,
    "color": "Mauv",
    "categorie": "wind",
    "brand": "Peavey"
  },
  {
    "id": "8f04d93d-5189-482b-bf1b-9d6e712d05ed",
    "name": "Tarka",
    "price": 158,
    "descript": "transform mission-critical experiences",
    "image": "https://robohash.org/autquiadelectus.png?size=50x50&set=set1",
    "stock": 3,
    "color": "Violet",
    "categorie": "electrophones",
    "brand": "Squier"
  },
  {
    "id": "24f95cea-256c-42a2-8df5-f1430c1ced1a",
    "name": "Flauta",
    "price": 288,
    "descript": "visualize robust e-business",
    "image": "https://robohash.org/reprehenderitdictafugit.png?size=50x50&set=set1",
    "stock": 6,
    "color": "Purple",
    "categorie": "percussion",
    "brand": "Yamaha"
  },
  {
    "id": "507ccbd2-3429-4bdd-b8a3-6867f99297bb",
    "name": "Liras",
    "price": 326,
    "descript": "productize cross-platform infrastructures",
    "image": "https://robohash.org/estenimasperiores.png?size=50x50&set=set1",
    "stock": 9,
    "color": "Indigo",
    "categorie": "wind",
    "brand": "Fender"
  },
  {
    "id": "3d6a8a42-97b3-48d8-8be5-63acac55ed2d",
    "name": "Guitarra",
    "price": 460,
    "descript": "maximize customized vortals",
    "image": "https://robohash.org/velitdoloribusrepudiandae.png?size=50x50&set=set1",
    "stock": 12,
    "color": "Crimson",
    "categorie": "string",
    "brand": "Gibson"
  },
  {
    "id": "c7ef7b84-8a93-4047-b9d1-eba110aa9a3b",
    "name": "Matraca",
    "price": 392,
    "descript": "generate customized networks",
    "image": "https://robohash.org/eveniettemporasoluta.png?size=50x50&set=set1",
    "stock": 6,
    "color": "Red",
    "categorie": "electrophones",
    "brand": "Squier"
  },
  {
    "id": "e5c6cc57-1a91-43f8-a14a-a6a1c020fc2b",
    "name": "Viola eléctrica",
    "price": 381,
    "descript": "deploy magnetic mindshare",
    "image": "https://robohash.org/dictaquosmaiores.png?size=50x50&set=set1",
    "stock": 12,
    "color": "Green",
    "categorie": "string",
    "brand": "Yamaha"
  },
  {
    "id": "fffff04b-0709-4ee4-affd-adf89babdaa7",
    "name": "Campana",
    "price": 395,
    "descript": "aggregate enterprise vortals",
    "image": "https://robohash.org/repellataddolor.png?size=50x50&set=set1",
    "stock": 17,
    "color": "Purple",
    "categorie": "percussion",
    "brand": "PRS"
  },
  {
    "id": "1d104378-3011-441c-88f7-b0f3422f1d16",
    "name": "Tarka",
    "price": 166,
    "descript": "expedite wireless technologies",
    "image": "https://robohash.org/auttotamsit.png?size=50x50&set=set1",
    "stock": 1,
    "color": "Aquamarine",
    "categorie": "wind",
    "brand": "Peavey"
  },
  {
    "id": "77dd6450-849e-45a1-8368-5569ac3fae1a",
    "name": "Castañuelas",
    "price": 197,
    "descript": "matrix open-source content",
    "image": "https://robohash.org/minusmolestiassit.png?size=50x50&set=set1",
    "stock": 15,
    "color": "Maroon",
    "categorie": "electrophones",
    "brand": "Peavey"
  },
  {
    "id": "6b5268db-5111-44aa-a151-967d763e4df3",
    "name": "Piano bajo",
    "price": 188,
    "descript": "matrix user-centric solutions",
    "image": "https://robohash.org/perferendisautemeum.png?size=50x50&set=set1",
    "stock": 13,
    "color": "Khaki",
    "categorie": "idiophones",
    "brand": "Gibson"
  },
  {
    "id": "b4acb7d2-7c74-43a9-974f-9bf4e529214f",
    "name": "Balalaika",
    "price": 204,
    "descript": "matrix integrated infrastructures",
    "image": "https://robohash.org/remconsequaturdolores.png?size=50x50&set=set1",
    "stock": 11,
    "color": "Khaki",
    "categorie": "string",
    "brand": "Gibson"
  },
  {
    "id": "dd0cc493-f1e6-4eef-9f00-d6bd960519dc",
    "name": "Dulzaina",
    "price": 364,
    "descript": "iterate scalable experiences",
    "image": "https://robohash.org/ducimuscorruptiest.png?size=50x50&set=set1",
    "stock": 12,
    "color": "Orange",
    "categorie": "string",
    "brand": "Peavey"
  },
  {
    "id": "2b2cba37-b579-405d-b6c5-63fb3118ebf4",
    "name": "Tambor",
    "price": 193,
    "descript": "reintermediate interactive mindshare",
    "image": "https://robohash.org/rationeutnemo.png?size=50x50&set=set1",
    "stock": 11,
    "color": "Pink",
    "categorie": "wind",
    "brand": "Yamaha"
  },
  {
    "id": "69a88faf-8eeb-4724-ac0c-073577bc0814",
    "name": "Liras",
    "price": 120,
    "descript": "integrate vertical networks",
    "image": "https://robohash.org/voluptatumpariaturdolor.png?size=50x50&set=set1",
    "stock": 10,
    "color": "Teal",
    "categorie": "wind",
    "brand": "Fender"
  },
  {
    "id": "3c4b26b5-8594-4422-9a07-e0ecec9e1c54",
    "name": "Arpa",
    "price": 181,
    "descript": "whiteboard bricks-and-clicks architectures",
    "image": "https://robohash.org/repellendussintaut.png?size=50x50&set=set1",
    "stock": 15,
    "color": "Red",
    "categorie": "electrophones",
    "brand": "Fender"
  },
  {
    "id": "27c7a88b-b81c-4485-8476-d1bab25249a6",
    "name": "Dulzaina",
    "price": 138,
    "descript": "empower collaborative infrastructures",
    "image": "https://robohash.org/uttemporibusdignissimos.png?size=50x50&set=set1",
    "stock": 18,
    "color": "Green",
    "categorie": "idiophones",
    "brand": "Gibson"
  },
  {
    "id": "802ad590-93ae-4ec0-a0ed-9a228bf8e711",
    "name": "Guitarra de acero de consola",
    "price": 270,
    "descript": "harness extensible web-readiness",
    "image": "https://robohash.org/necessitatibusatquevel.png?size=50x50&set=set1",
    "stock": 10,
    "color": "Violet",
    "categorie": "percussion",
    "brand": "Peavey"
  },
  {
    "id": "0105456d-22a3-4a27-b937-4c573936da10",
    "name": "Bongó",
    "price": 233,
    "descript": "synthesize back-end web services",
    "image": "https://robohash.org/solutafugiatsapiente.png?size=50x50&set=set1",
    "stock": 15,
    "color": "Green",
    "categorie": "percussion",
    "brand": "Fender"
  },
  {
    "id": "0a8961d3-b6d4-47ef-b297-1088f95f3e46",
    "name": "Flauta",
    "price": 374,
    "descript": "redefine one-to-one schemas",
    "image": "https://robohash.org/similiquequoomnis.png?size=50x50&set=set1",
    "stock": 3,
    "color": "Blue",
    "categorie": "idiophones",
    "brand": "Squier"
  },
  {
    "id": "b33f62c7-164e-4df5-8685-49632cd45041",
    "name": "Batería",
    "price": 158,
    "descript": "streamline front-end infomediaries",
    "image": "https://robohash.org/autmolestiaemaxime.png?size=50x50&set=set1",
    "stock": 1,
    "color": "Maroon",
    "categorie": "electrophones",
    "brand": "Squier"
  }
]`